#!/usr/bin/env python3
"""Generate single-header lunar_log.hpp from the multi-file include tree."""

import re
import os

INCLUDE_DIR = os.path.join(os.path.dirname(__file__), "..", "include")
OUTPUT = os.path.join(
    os.path.dirname(__file__), "..", "single_include", "lunar_log.hpp"
)

# Ordered list matching include/lunar_log.hpp
HEADERS = [
    "lunar_log/core/log_level.hpp",
    "lunar_log/core/log_common.hpp",
    "lunar_log/core/log_entry.hpp",
    "lunar_log/core/filter_rule.hpp",
    "lunar_log/core/compact_filter.hpp",
    "lunar_log/core/rolling_policy.hpp",
    "lunar_log/transform/pipe_transform.hpp",
    "lunar_log/formatter/formatter_interface.hpp",
    "lunar_log/formatter/human_readable_formatter.hpp",
    "lunar_log/formatter/json_detail.hpp",
    "lunar_log/formatter/json_formatter.hpp",
    "lunar_log/formatter/compact_json_formatter.hpp",
    "lunar_log/formatter/xml_formatter.hpp",
    "lunar_log/transport/transport_interface.hpp",
    "lunar_log/transport/file_transport.hpp",
    "lunar_log/transport/stdout_transport.hpp",
    "lunar_log/sink/sink_interface.hpp",
    "lunar_log/sink/console_sink.hpp",
    "lunar_log/sink/color_console_sink.hpp",
    "lunar_log/sink/file_sink.hpp",
    "lunar_log/sink/rolling_file_sink.hpp",
    "lunar_log/log_manager.hpp",
    "lunar_log/log_source.hpp",
    "lunar_log/macros.hpp",
]

LOCAL_INCLUDE = re.compile(r'^\s*#include\s+"[^"]*"')
GUARD_IFNDEF = re.compile(r"^\s*#ifndef\s+\w+")
GUARD_DEFINE = re.compile(r"^\s*#define\s+\w+_(?:HPP|H)\b")
GUARD_ENDIF = re.compile(r"^\s*#endif\s*//\s*\w+_(?:HPP|H)\b")


def strip_guards_and_local_includes(lines):
    """Remove include guards and local #include directives."""
    out = []
    # skip first #ifndef / #define pair
    i = 0
    while i < len(lines):
        if GUARD_IFNDEF.match(lines[i]):
            # skip this and next #define line
            if i + 1 < len(lines) and GUARD_DEFINE.match(lines[i + 1]):
                i += 2
                continue
        break

    # process body, skip last #endif guard
    body = lines[i:]
    # remove trailing #endif guard
    while body and body[-1].strip() == "":
        body.pop()
    if body and GUARD_ENDIF.match(body[-1]):
        body.pop()

    for line in body:
        if LOCAL_INCLUDE.match(line):
            continue
        out.append(line)
    return out


def main():
    """Concatenate all headers into a single self-contained lunar_log.hpp."""
    parts = []
    parts.append("// LunarLog - Single Header")
    parts.append("// https://github.com/LunarECL/LunarLog")
    parts.append("// Auto-generated by tools/generate_single_header.py")
    parts.append("//")
    parts.append("// Usage: just include this file.")
    parts.append("")
    parts.append("#ifndef LUNAR_LOG_SINGLE_HEADER_HPP")
    parts.append("#define LUNAR_LOG_SINGLE_HEADER_HPP")
    parts.append("")

    for header in HEADERS:
        path = os.path.join(INCLUDE_DIR, header)
        with open(path) as f:
            lines = f.readlines()
        cleaned = strip_guards_and_local_includes(lines)
        parts.append(f"// --- {header} ---")
        parts.extend(line.rstrip() for line in cleaned)
        parts.append("")

    parts.append("#define LUNAR_LOG_CONTEXT __FILE__, __LINE__, __func__")
    parts.append("")
    parts.append("#endif // LUNAR_LOG_SINGLE_HEADER_HPP")
    parts.append("")

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w") as f:
        f.write("\n".join(parts))

    line_count = len(parts)
    print(f"Generated {OUTPUT} ({line_count} lines)")


if __name__ == "__main__":
    main()
